def treeomics_run(idir, odir, fmutread, fcoverage, hgver, nthreads):
    '''
    TREEOMICS: reconstruct the tumor mutation phylogeny
    
    COMMAND:
    treeomics_run(idir = './, odir='./', fmutread, fcoverage, hgver, nthreads)

    INPUT: 
        idir       : /path/idir/
        odir       : /path/odir/
        *fmutread  : mut_read.txt 
        *fcoverage : coverage.txt 
            *generated by treeomics_input.py modules
        hgver      : hg37, hg38, human genome version
        nthreads   : number of threads

    OUTPUT:
    Generate Two Input files for TREEOMICS from Annotated VCF file


    '''
    os.system(f'treeomics -r {idir}{fmutread} -s {idir}{fcoverage} -o {odir} -g {hgver} --threads {nthreads}')
    print(f"Successfully generated:\n\t1: {odir}/")
